services:
  - type: web
    name: kairo-01
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn main:app"
    envVars:
      - key: OPENAI_API_KEY
        sync: false